### ISSUE TITLE
Compatability with other Forks?

### ISSUE THREAD

**Issue by aero31aero** [GhettoGirl/markdown-editor#1]
Not exactly an issue, but an inquiry. I don't know how electron works so I am not able to judge for myself. Will it be compatible with other forks? I plan on adding a parallel electron branch to [my fork](http://github.com/aero31aero/markdown-editor/). Thanks.

**Comment by GhettoGirl** [comment]
Not exactly an compatability issue. But I never planned to maintain or improve this, just quickly wrap this into an Electron app so I don't need to use that thing in a web browser.

Do whatever you want in your fork and ignore mine. If yours turns out to be better integrated into the Desktop (file load/save dialog, etc.) I will use it and delete my fork :)

Regards
